version: '3.8'

services:
  silentbot:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: node silentbot.js
    environment:
      - NODE_ENV=production
    networks:
      - silentbot-network
    restart: unless-stopped

networks:
  silentbot-network:
